export const PAYMENT_FAIL = 'PAYMENT_FAIL';
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';

export const ORDER_FAIL = 'ORDER_FAIL';
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';

export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL';
export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
